FROM eclipse-temurin:21-jdk-alpine

WORKDIR /workspace/backend

RUN apk add --no-cache curl

COPY gradlew .
COPY gradle/wrapper ./gradle/wrapper
COPY build.gradle.kts settings.gradle.kts ./

RUN chmod +x ./gradlew
RUN ./gradlew dependencies --no-daemon

COPY . .

EXPOSE 8080
CMD ["sh", "-c", "chmod +x ./gradlew && ./gradlew bootRun --no-daemon"]