FROM eclipse-temurin:21-jdk-alpine

WORKDIR /workspace/backend

RUN apk add --no-cache curl

COPY gradlew .
COPY gradle/wrapper ./gradle/wrapper
COPY build.gradle.kts settings.gradle.kts ./

RUN chmod +x ./gradlew
RUN ./gradlew clean build -x test --no-daemon || echo "Skipping failed build (intended for dependency caching)"

COPY . .

EXPOSE 8080
CMD ["sh", "-c", "chmod +x ./gradlew && ./gradlew classes --continuous --no-daemon & ./gradlew bootRun --no-daemon"]