name: Verify Backend Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    name: Check Paths For Changes
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      backend_changed: ${{ steps.changes.outputs.backend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Detect file changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'

  verify-backend:
    name: Verify Backend Changes
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle

      - name: Grant execute permissions for Gradle
        working-directory: backend
        run: chmod +x gradlew

      - name: Run Ktlint check
        working-directory: backend
        run: ./gradlew ktlintCheck --no-daemon

      - name: Run tests
        working-directory: backend
        run: ./gradlew test --no-daemon

      - name: Assemble project
        working-directory: backend
        run: ./gradlew clean assemble --no-daemon
